Bump cardano-node, use aeson 2, and use cabal as source of truth
Co-Authored-By: Hamish Mackenzie <Hamish.K.Mackenzie@gmail.com>
Co-Authored-By: Evgenii Akentev <i@ak3n.com>
Co-Authored-By: Samuel Evans-Powell <mail@sevanspowell.net>
Co-Authored-By: Johannes Lund <johannes.lund@iohk.io>

Squashed from:

- Update hackageNix + flake
- Bump iohk-nix
- Initial attempts at bumping dependencies
- Ensure we're using ghc-8.10.7
- Try using cabal.project as source of truth
- Explore alternative path: tweak existing LTS
- Make `stackProject` and `cabalProject` work the same.
- Remove stack-nix materialization
    This fixes this error from running ./nix/regenerate.sh:

    ```
    error: attribute 'stack-nix' missing

           at /nix/store/flpvyc5zbczv3zmspqylpmpmq2sh3wwq-source/flake.nix:371:24:

              370|               inherit (pkgs) sha256map-regenerate checkStackProject;
              371|               inherit (project.stack-nix.passthru) generateMaterialized;
                 |                        ^
              372|               buildToolsGenerateMaterialized = pkgs.haskell-build-tools.regenerateMaterialized;
    ```

    Which we need to be able to run to bump dependencies (ran into this when
    bumping cardano-addresses in another, to-be future commit)

- Tweak MonadSTM instance
- Update to aeson2 and partially to recent cardano-node
- Bump cardano-addresses
- Partially bump node again
- Start filling in some Babbage glue
- Fix cardano-wallet-core haddock comments
- Fix genTxIx
  Fixes several test failures of type

      Transaction input index is too big, acceptable value is up to 2^32-1, in input TxIn "01f4b788593d4f70de2a45c2e1e87088bfbdfa29577ae1b62aba60e095e3ab53" (TxIx 18446744073709551615)
- fix warnings
- Make TPraos type parameters concrete
- fixups