Cabal: Add version constraints on persistent
The cabal build was failing due to:

    src/Cardano/Pool/DB/Sqlite/TH.hs:50:7: error: [-Wdeprecations, -Werror=deprecations]
    In the use of ‘mkDeleteCascade’
    (imported from Database.Persist.TH):
    Deprecated: "You can now set update and delete cascade behavior directly on the entity in the quasiquoter. This function and class are deprecated and will be removed in the next major ersion."
    \|
    50 \|     , mkDeleteCascade sqlSettings'
    \|       ^^^^^^^^^^^^^^^
    cabal: Failed to build cardano-wallet-core-2021.6.11 (which is required by
    bench:restore from cardano-wallet-2021.6.11, exe:local-cluster from
    cardano-wallet-2021.6.11 and others).

We will need to adjust our code to work with newer versions of
persistent, once we update to Stackage LTS 18.*.

Resolves #2742