cli: Use Paths module to get program version
embedFile wasn't working for me in ghci.

  lib/cli/src/Cardano/CLI.hs:275:27: error:
      • Exception when trying to run compile-time code:
          ../../cardano-wallet.cabal: openBinaryFile: does not exist (No such file or directory)
        Code: embedFile "../../cardano-wallet.cabal"
      • In the untyped splice: $(embedFile "../../cardano-wallet.cabal")
      |
  275 |     let cabal = B8.unpack $(embedFile "../../cardano-wallet.cabal")
      |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

There is another easier way to get the program version (assuming all
cabal files have the same version).