Ensure git is in PATH when building cardano-wallet-core library
- This is to overcome the following error when building cardano-config, a
dependency:

```
src/Cardano/Config/Git/Rev.hs:33:35: error:
    • Exception when trying to run compile-time code:
        git: readCreateProcessWithExitCode: posix_spawnp: failed (Undefined error: 0)
      Code: gitRevFromGit
    • In the untyped splice: $(gitRevFromGit)
   |
33 |         fromGit = T.strip (T.pack $(gitRevFromGit))
```

That is, the Template Haskell was failing to compile because it did not have git
in PATH.
- Note the repeated "buildPackages" attr. This snippet was provided by Hamish
Mackenzie, who said that it's "because git had (think it still might) a
dependency on python and that depended on gdb and as a result when cross
compiling buildPackages.git and buildPackages.buildPackages.git were subtly
different (causing cache misses). I am not sure if it is a problem with
gitMinimal but it might be."