Remove stack-nix materialization
This fixes this error from running ./nix/regenerate.sh:

```
error: attribute 'stack-nix' missing

       at /nix/store/flpvyc5zbczv3zmspqylpmpmq2sh3wwq-source/flake.nix:371:24:

          370|               inherit (pkgs) sha256map-regenerate checkStackProject;
          371|               inherit (project.stack-nix.passthru) generateMaterialized;
             |                        ^
          372|               buildToolsGenerateMaterialized = pkgs.haskell-build-tools.regenerateMaterialized;
```

Which we need to be able to run to bump dependencies (ran into this when
bumping cardano-addresses in another, to-be future commit)